# https://shom.dev/posts/20220514_from-fish-on-gnome-terminal-to-zsh-with-starship-on-alacritty/

# https://github.com/catppuccin/alacritty
[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = ["catppuccin-macchiato.toml"]

[window]
opacity = 0.95

  [window.padding]
  x = 10
  y = 5

[font]
size = 12

  [font.normal]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"

[cursor]
vi_mode_style = "Underline"
thickness = 0.25

  [cursor.style]
  shape = "Beam"

[keyboard]

[[keyboard.bindings]]
key = "N"
mods = "Shift|Control"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullScreen"
